@@include('../component/dropDownLlist/js/dropDownList.js')
@@include('../component/dinamicAdaptiv/js/dinamicAdaptiv.js')
@@include('../component/Quantity/js/quantity.js')
@@include('libs/nouislider.js')
@@include('libs/wNumb.min.js')
